export const tileSets = {
  animals: [
    { id: '1', value: '🐶' },
    { id: '2', value: '🐵' },
    { id: '3', value: '😺' },
    { id: '4', value: '🐘' },
    { id: '5', value: '🦁' },
    { id: '6', value: '🐯' },
    { id: '7', value: '🦒' },
    { id: '8', value: '🦊' },
    { id: '9', value: '🦝' },
    { id: '10', value: '🐮' },
    { id: '11', value: '🐷' },
    { id: '12', value: '🐗' },
    { id: '13', value: '🐺' },
    { id: '14', value: '🐭' },
    { id: '15', value: '🐹' },
    { id: '16', value: '🐰' },
    { id: '17', value: '🐻' },
    { id: '18', value: '🐻‍❄️' },
    { id: '19', value: '🐨' },
    { id: '20', value: '🐼' },
    { id: '21', value: '🐸' },
    { id: '22', value: '🦓' },
    { id: '23', value: '🐴' },
    { id: '24', value: '🫎' },
    { id: '25', value: '🫏' },
    { id: '26', value: '🦄' },
    { id: '27', value: '🐔' },
    { id: '28', value: '🐲' },
    { id: '29', value: '🐒' },
    { id: '30', value: '🦍' },
    { id: '31', value: '🦧' },
    { id: '32', value: '🦮' },
    { id: '33', value: '🐩' },
    { id: '34', value: '🐕' },
    { id: '35', value: '🐈' },
    { id: '36', value: '🐈‍⬛' },
    { id: '37', value: '🐅' },
    { id: '38', value: '🐆' },
    { id: '39', value: '🐎' },
    { id: '40', value: '🦌' },
    { id: '41', value: '🦬' },
    { id: '42', value: '🦏' },
    { id: '43', value: '🦛' },
    { id: '44', value: '🐂' },
    { id: '45', value: '🐃' },
    { id: '46', value: '🐄' },
    { id: '47', value: '🐖' },
    { id: '48', value: '🐏' },
    { id: '49', value: '🐑' },
    { id: '50', value: '🦆' },
    { id: '51', value: '🐓' },
    { id: '52', value: '🦜' },
    { id: '53', value: '🦢' },
    { id: '54', value: '🦃' },
    { id: '55', value: '🦅' },
    { id: '56', value: '🦉' },
    { id: '57', value: '🐥' },
    { id: '58', value: '🐞' },
    { id: '59', value: '🐦‍🔥' },
    { id: '59', value: '🐦‍⬛' },
  ],
  emoji: [
    { id: '1', value: '😎' },
    { id: '2', value: '😂' },
    { id: '3', value: '🤣' },
    { id: '4', value: '😃' },
    { id: '5', value: '😄' },
    { id: '6', value: '😅' },
    { id: '7', value: '😆' },
    { id: '8', value: '😉' },
    { id: '9', value: '😊' },
    { id: '10', value: '😋' },
    { id: '11', value: '😁' },
    { id: '12', value: '😍' },
    { id: '13', value: '😘' },
    { id: '14', value: '🥰' },
    { id: '15', value: '😗' },
    { id: '16', value: '😙' },
    { id: '17', value: '🥲' },
    { id: '18', value: '😚' },
    { id: '19', value: '☺️' },
    { id: '20', value: '🙂' },
    { id: '21', value: '🤗' },
    { id: '22', value: '🤩' },
    { id: '23', value: '🤔' },
    { id: '24', value: '🫡' },
    { id: '25', value: '🤨' },
    { id: '26', value: '😐' },
    { id: '27', value: '😑' },
    { id: '28', value: '😶' },
    { id: '29', value: '🫥' },
    { id: '30', value: '😶‍🌫️' },
    { id: '31', value: '🙄' },
    { id: '32', value: '😏' },
    { id: '33', value: '😣' },
    { id: '34', value: '😥' },
    { id: '35', value: '😮' },
    { id: '36', value: '🤐' },
    { id: '37', value: '😯' },
    { id: '38', value: '😪' },
    { id: '39', value: '😫' },
    { id: '40', value: '🥱' },
    { id: '41', value: '😴' },
    { id: '42', value: '😌' },
    { id: '43', value: '😛' },
    { id: '44', value: '😜' },
    { id: '45', value: '😝' },
    { id: '46', value: '🤤' },
    { id: '47', value: '😒' },
    { id: '48', value: '😓' },
    { id: '49', value: '😔' },
    { id: '50', value: '😕' },
    { id: '51', value: '🫤' },
    { id: '52', value: '🙃' },
    { id: '53', value: '🫠' },
    { id: '54', value: '🤑' },
    { id: '55', value: '😲' },
    { id: '56', value: '☹️' },
    { id: '57', value: '🙁' },
    { id: '58', value: '😖' },
    { id: '59', value: '😞' },
    { id: '60', value: '😤' },
    { id: '61', value: '😢' },
    { id: '62', value: '😭' },
    { id: '63', value: '😦' },
    { id: '64', value: '😨' },
    { id: '65', value: '😩' },
    { id: '66', value: '🤯' },
    { id: '67', value: '😬' },
    { id: '68', value: '😮‍💨' },
    { id: '69', value: '😱' },
    { id: '70', value: '😟' },
    { id: '71', value: '🥵' },
    { id: '72', value: '🥶' },
    { id: '73', value: '🤪' },
    { id: '74', value: '😵' },
    { id: '75', value: '😵‍💫' },
    { id: '76', value: '🥴' },
    { id: '77', value: '😡' },
    { id: '78', value: '😷' },
    { id: '79', value: '🤒' },
    { id: '80', value: '🤕' },
    { id: '81', value: '🤢' },
    { id: '82', value: '🤮' },
    { id: '83', value: '🤧' },
    { id: '84', value: '😇' },
    { id: '85', value: '🥳' },
    { id: '86', value: '🥸' },
    { id: '87', value: '🥺' },
    { id: '88', value: '🤠' },
    { id: '89', value: '🤡' },
    { id: '90', value: '🤥' },
    { id: '91', value: '🫨' },
    { id: '92', value: '🙂‍↔️' },
    { id: '93', value: '🙂‍↕️' },
    { id: '94', value: '🤫' },
    { id: '95', value: '🤭' },
    { id: '96', value: '🫢' },
    { id: '97', value: '🫣' },
    { id: '98', value: '🧐' },
    { id: '99', value: '🤓' },
  ],
  food: [
    { id: '1', value: '🍕' },
    { id: '2', value: '🍔' },
    { id: '3', value: '🍟' },
    { id: '4', value: '🌭' },
    { id: '5', value: '🍿' },
    { id: '6', value: '🧂' },
    { id: '7', value: '🧈' },
    { id: '8', value: '🥞' },
    { id: '9', value: '🧇' },
    { id: '10', value: '🍳' },
    { id: '11', value: '🥚' },
    { id: '12', value: '🥓' },
    { id: '13', value: '🍞' },
    { id: '14', value: '🥐' },
    { id: '15', value: '🥨' },
    { id: '16', value: '🥯' },
    { id: '17', value: '🥖' },
    { id: '18', value: '🫓' },
    { id: '19', value: '🌯' },
    { id: '20', value: '🌮' },
  ],
};

// 🥪
// 🥙
// 🥗
// 🧀
// 🫔
// 🥫
// 🍖
// 🍗
// 🥩
// 🍠
